# Generated by Django 3.1.3 on 2020-11-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201129_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/card-thumnail.jpg', null=True, upload_to=''),
        ),
    ]
