# Generated by Django 3.1.3 on 2020-11-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201129_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/card-thumbnail.jpg', null=True, upload_to='images'),
        ),
    ]
