# Generated by Django 3.1.3 on 2020-11-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201129_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/card-thumbnail.jpg', null=True, upload_to=''),
        ),
    ]
